force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSheet_Setting__c/TimeSheet_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Basic Setting for timeSheet</description>
    <label>TimeSheet Setting</label>
</CustomObject>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Custom_Hoilday__c.field-meta.xml
<CustomField>
    <fullName>Custom_Hoilday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Hoilday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Custom_Leave__c.field-meta.xml
<CustomField>
    <fullName>Custom_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Date_Only__c.field-meta.xml
<CustomField>
    <fullName>Date_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Show Date only on  the label ,like 2019-2-11</inlineHelpText>
    <label>Date Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Day_Only__c.field-meta.xml
<CustomField>
    <fullName>Day_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show Day as Label ,example Monday,Tueday</description>
    <inlineHelpText>Show Day as Label ,example Monday,Tueday</inlineHelpText>
    <label>Day Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Default_Interval__c.field-meta.xml
<CustomField>
    <fullName>Default_Interval__c</fullName>
    <label>Default Interval</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Disable_Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Disable_Approval_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Approval Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Disable_Overlap__c.field-meta.xml
<CustomField>
    <fullName>Disable_Overlap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Overlap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/EmployeeField__c.field-meta.xml
<CustomField>
    <fullName>EmployeeField__c</fullName>
    <description>The field hold the Lookup field name for the employee for which the time entry will be done.</description>
    <inlineHelpText>The field hold the Lookup field name for the employee for which the time entry will be done.By default the user will be the employee but some can choose other object.</inlineHelpText>
    <label>Employee Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Entry_Project_Field__c.field-meta.xml
<CustomField>
    <fullName>Entry_Project_Field__c</fullName>
    <label>Entry Project Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Entry_Task_Field__c.field-meta.xml
<CustomField>
    <fullName>Entry_Task_Field__c</fullName>
    <label>Entry Task Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Hide_Task__c.field-meta.xml
<CustomField>
    <fullName>Hide_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Holiday_Check__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Holiday Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Leave_Check__c.field-meta.xml
<CustomField>
    <fullName>Leave_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leave Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Project_Field__c.field-meta.xml
<CustomField>
    <fullName>Project_Field__c</fullName>
    <description>The Project is to override the Project lookup on TimeSheet, Admin can create lookup on TimeSheet for any sobject and put the field name in the field to use the sobejct as Project.By default TimeSheet-Project is used.</description>
    <inlineHelpText>The Project is to override the Project lookup on TimeSheet, Admin can create lookup on TimeSheet for any sobject and put the field name in the field to use the sobejct as Project.By default TimeSheet-Project is used.</inlineHelpText>
    <label>Project Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet_Setting__c/fields/Week_Start_Day__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Day__c</fullName>
    <label>Week Start Day</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BaseSettingService.cls
public virtual class BaseSettingService {

    public TimeSheet_Setting__c BaseSetting;
    
    public virtual  void fetchRecord(){
        set<string> fields=Utility.getFields('TimeSheet_Setting__c');
        string query=Utility.createQuery(fields,'TimeSheet_Setting__c');
        
        list<TimeSheet_Setting__c> BaseSettinglist=database.query(query);
        if(BaseSettinglist.size()>0){
            BaseSetting=BaseSettinglist[0];
        }
    }
    
    public string saveBasicSetting(string BasicSetting){
        string result='';
        
        try{
            system.debug('****************BasicSetting'+BasicSetting);
            Setting sst=(Setting)JSON.deserialize(BasicSetting, Setting.class);
            system.debug('*****************sst'+sst);
            
            if(sst!=null){
                
                TimeSheet_Setting__c BaseSetting=new TimeSheet_Setting__c();
                
                if(sst.recordId!=null && sst.recordId!='')
                    BaseSetting.Id= sst.recordId;
                
                BaseSetting.Custom_Hoilday__c=sst.CustomHoilday;         
                BaseSetting.Custom_Leave__c=sst.CustomLeave;
                BaseSetting.Default_Interval__c=sst.DefaultInterval;           
                BaseSetting.Disable_Approval_Process__c=sst.DisableApprovalProcess;
                BaseSetting.Disable_Overlap__c=sst.DisableOverlap;
                BaseSetting.EmployeeField__c=sst.EmployeeField;
                BaseSetting.Entry_Project_Field__c=sst.EntryProjectField;
                BaseSetting.Entry_Task_Field__c=sst.EntryTaskField;
                BaseSetting.Hide_Task__c=sst.HideTask;
                BaseSetting.Holiday_Check__c=sst.HolidayCheck;
                BaseSetting.Leave_Check__c= sst.LeaveCheck;   
                BaseSetting.Project_Field__c=sst.ProjectField;
                BaseSetting.Show_Weekend__c=sst.ShowWeekend;
                BaseSetting.Task_Required__c=sst.TaskRequired;
                BaseSetting.Week_Start_Day__c=sst.WeekStartDay;
                
                BaseSetting.Date_Only__c=sst.DateOnly;
                BaseSetting.Day_Only__c=sst.DayOnly;
                BaseSetting.Short_Day_with_Date__c=sst.ShortDaywithDate;
                
                if(BaseSetting.Id!=null)
                    update BaseSetting;
                else 
                    insert BaseSetting;
            }
        }catch(exception e){
            result=e.getmessage();
        }
        
        return result;
    }
    
    public virtual Setting getTimeSheetSetting(){
       
        Setting sst=new Setting();
        
            
        fetchRecord();
        
        if(BaseSetting!=null){
            sst.recordId=BaseSetting.Id;
            sst.CustomHoilday=BaseSetting.Custom_Hoilday__c;         
            sst.CustomLeave=BaseSetting.Custom_Leave__c;
            sst.DefaultInterval=BaseSetting.Default_Interval__c;           
            sst.DisableApprovalProcess=BaseSetting.Disable_Approval_Process__c;
            sst.DisableOverlap=BaseSetting.Disable_Overlap__c;
            sst.EmployeeField=BaseSetting.EmployeeField__c;
            sst.EntryProjectField=BaseSetting.Entry_Project_Field__c;
            sst.EntryTaskField=BaseSetting.Entry_Task_Field__c;
            sst.HideTask=BaseSetting.Hide_Task__c;
            sst.HolidayCheck=BaseSetting.Holiday_Check__c;
            sst.LeaveCheck=BaseSetting.Leave_Check__c;   
            sst.ProjectField=BaseSetting.Project_Field__c;
            sst.ShowWeekend=BaseSetting.Show_Weekend__c;
            sst.TaskRequired=BaseSetting.Task_Required__c;
            sst.WeekStartDay=BaseSetting.Week_Start_Day__c;
            sst.DateOnly=BaseSetting.Date_Only__c;
            sst.DayOnly=BaseSetting.Day_Only__c;
            sst.ShortDaywithDate=BaseSetting.Short_Day_with_Date__c;
        }else{
           
            //SET DEFAULT VALUE
     
            sst.CustomHoilday=false;         
            sst.CustomLeave=false;
            sst.DefaultInterval='WEEK';           
            sst.DisableApprovalProcess=false;
            sst.DisableOverlap=true;
            sst.EmployeeField='Employee__c';
            sst.EntryProjectField='Assignment__c';
            sst.EntryTaskField='Task__c';
            sst.HideTask=false;
            sst.HolidayCheck=false;
            sst.LeaveCheck=true;   
            sst.ProjectField='Assignment__c';
            sst.ShowWeekend=true;
            sst.TaskRequired=true;
            sst.WeekStartDay='SUNDAY'; 
            sst.DateOnly=true;
            sst.DayOnly=false;
            sst.ShortDaywithDate=false;
        }
        
        return sst;
    }
    
    public class Setting{    
        @auraEnabled
        public string recordId;   
        @auraEnabled
        public boolean CustomHoilday;
        @auraEnabled
        public boolean CustomLeave;
        @auraEnabled
        public string DefaultInterval;
        @auraEnabled
        public list<string> DefaultIntervals;
        @auraEnabled
        public boolean DisableApprovalProcess;
        @auraEnabled
        public boolean DisableOverlap;
        @auraEnabled
        public string EmployeeField;
        @auraEnabled
        public string EntryProjectField;
        @auraEnabled
        public string EntryTaskField;
        @auraEnabled
        public boolean HideTask;
        @auraEnabled
        public boolean HolidayCheck;
        @auraEnabled
        public boolean LeaveCheck;   
        @auraEnabled
        public string ProjectField;
        @auraEnabled
        public boolean ShowWeekend;
        @auraEnabled
        public boolean TaskRequired;
        @auraEnabled
        public string WeekStartDay;
        
        @auraEnabled
        public boolean DateOnly;
        @auraEnabled
        public boolean DayOnly;
        @auraEnabled
        public boolean ShortDaywithDate;
        
        @auraEnabled
        public boolean trial;
                
        public setting(){
            DefaultIntervals=new list<string>();
            DefaultIntervals.add('WEEK');
            DefaultIntervals.add('MONTH');
            DefaultIntervals.add('DAY');
            
            trial=true;
        }
    }
}